/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package week3;

import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Yavuuz
 */

//Liste içeriği oluşturma.
public class ListViewTransfer extends javax.swing.JFrame {
    DefaultListModel<String> modelLeft = new DefaultListModel<>();
    DefaultListModel<String> modelRight = new DefaultListModel<>();

    
    List<String> selectedValues;

    /**
     * Creates new form NewJFrame1
     */
    public ListViewTransfer() {
        initComponents();
        for (int i = 0; i < 5; i++) {
            modelLeft.addElement(i + "");
        }
        lst_first.setModel(modelLeft);
        for (int i = 5; i < 10; i++) {
            modelRight.addElement(i + "");
        }
        lst_second.setModel(modelRight);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lst_first = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_second = new javax.swing.JList<>();
        btn_leftToRight = new javax.swing.JButton();
        btn_rightToLeft = new javax.swing.JButton();
        btn_rightToAll = new javax.swing.JButton();
        btn_leftToAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lst_first.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1", "2", "3", "4", "5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lst_first);

        lst_second.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "6", "7", "8", "9", "10" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lst_second);

        btn_leftToRight.setText(">");
        btn_leftToRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_leftToRightActionPerformed(evt);
            }
        });

        btn_rightToLeft.setText("<");
        btn_rightToLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rightToLeftActionPerformed(evt);
            }
        });

        btn_rightToAll.setText(">>");
        btn_rightToAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rightToAllActionPerformed(evt);
            }
        });

        btn_leftToAll.setText("<<");
        btn_leftToAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_leftToAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_leftToRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_rightToLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_leftToAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_rightToAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btn_leftToRight)
                        .addGap(17, 17, 17)
                        .addComponent(btn_rightToLeft)
                        .addGap(17, 17, 17)
                        .addComponent(btn_rightToAll)
                        .addGap(17, 17, 17)
                        .addComponent(btn_leftToAll))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(195, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_leftToRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lefttorightActionPerformed
        // TODO add your handling code here:
        selectedValues = lst_first.getSelectedValuesList();
        for(String value: selectedValues){
            modelLeft.removeElement(value);
            modelRight.addElement(value);
        }
        lst_first.setModel(modelLeft);
        lst_second.setModel(modelRight);            
    
    }//GEN-LAST:event_btn_lefttorightActionPerformed

    private void btn_rightToLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rightToLeftActionPerformed
        // TODO add your handling code here:
        selectedValues = lst_second.getSelectedValuesList();
        for(String value: selectedValues){
            modelRight.removeElement(value);
            modelLeft.addElement(value);
        }
        lst_first.setModel(modelLeft);
        lst_second.setModel(modelRight);
    }//GEN-LAST:event_btn_rightToLeftActionPerformed

    private void btn_rightToAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rightToAllActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i < modelLeft.size(); i++){
            modelRight.addElement(modelLeft.get(i));
        }
        modelLeft.clear();
    }//GEN-LAST:event_btn_rightToAllActionPerformed

    private void btn_leftToAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_leftToAllActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i < modelRight.size(); i++){
            modelLeft.addElement(modelRight.get(i));
        }
        modelRight.clear();
    }//GEN-LAST:event_btn_leftToAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListViewTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListViewTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListViewTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListViewTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListViewTransfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_leftToAll;
    private javax.swing.JButton btn_leftToRight;
    private javax.swing.JButton btn_rightToAll;
    private javax.swing.JButton btn_rightToLeft;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lst_first;
    private javax.swing.JList<String> lst_second;
    // End of variables declaration//GEN-END:variables
}
